### ISSUE TITLE
Not working, issue with Auth

### ISSUE THREAD

**Issue by groundsada** [spegel-org/benchmark#65]
I cannot run the benchmark tool. I'm attempting to run it locally from an ARM Mac using benchmark_0.0.4_darwin_arm64

Using: `./benchmark measure --result-dir . --kubeconfig config --namespace my-namespace --images ghcr.io/spegel-org/benchmark:v1-10MB-1 ghcr.io/spegel-org/benchmark:v2-10MB-1`

I get: `unexpected error: no Auth Provider found for name "oidc"`

For more context, my k8s cluster uses OIDC for auth, this is what a sample config looks like:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERTIFICATE_AUTHORITY_DATA>
    server: https://<CLUSTER_SERVER_URL>:443
  name: <CLUSTER_NAME>
contexts:
- context:
    cluster: <CLUSTER_NAME>
    namespace: <NAMESPACE>
    user: <USER_URL>
  name: <CONTEXT_NAME>
current-context: <CONTEXT_NAME>
kind: Config
preferences: {}
users:
- name: <USER_URL>
  user:
    auth-provider:
      config:
        client-id: <CLIENT_ID>
        client-secret: <CLIENT_SECRET>
        id-token: <ID_TOKEN>
        idp-issuer-url: https://<IDP_ISSUER_URL>/application/o/k8s/
        refresh-token: <REFRESH_TOKEN>
      name: oidc
```
